# Generated by Django 4.2.2 on 2023-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
